{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ton-k8s-operator.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ton-k8s-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ton-k8s-operator.fullname" . }}-manager-role
  labels:
    {{- include "ton-k8s-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ton.ton.org
    resources:
      - tonnodes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ton.ton.org
    resources:
      - tonnodes/finalizers
    verbs:
      - update
  - apiGroups:
      - ton.ton.org
    resources:
      - tonnodes/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ton-k8s-operator.fullname" . }}-metrics-auth-role
  labels:
    {{- include "ton-k8s-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ton-k8s-operator.fullname" . }}-metrics-reader
  labels:
    {{- include "ton-k8s-operator.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ton-k8s-operator.fullname" . }}-tonnode-admin-role
  labels:
    {{- include "ton-k8s-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ton.ton.org
    resources:
      - tonnodes
    verbs:
      - "*"
  - apiGroups:
      - ton.ton.org
    resources:
      - tonnodes/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ton-k8s-operator.fullname" . }}-tonnode-editor-role
  labels:
    {{- include "ton-k8s-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ton.ton.org
    resources:
      - tonnodes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ton.ton.org
    resources:
      - tonnodes/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ton-k8s-operator.fullname" . }}-tonnode-viewer-role
  labels:
    {{- include "ton-k8s-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ton.ton.org
    resources:
      - tonnodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ton.ton.org
    resources:
      - tonnodes/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ton-k8s-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ton-k8s-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ton-k8s-operator.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "ton-k8s-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ton-k8s-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "ton-k8s-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ton-k8s-operator.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "ton-k8s-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ton-k8s-operator.fullname" . }}-metrics-auth-rolebinding
  labels:
    {{- include "ton-k8s-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ton-k8s-operator.fullname" . }}-metrics-auth-role
subjects:
  - kind: ServiceAccount
    name: {{ include "ton-k8s-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
