apiVersion: ton.ton.org/v1alpha1
kind: TonNode
metadata:
  labels:
    app.kubernetes.io/name: ton-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: tonnode
spec:
  image: ghcr.io/ton-blockchain/ton-docker-ctrl:v2026.04-amd64
  replicas: 3
  storage:
    tonWorkSize: 200Gi
    myTonCoreSize: 20Gi
  network:
    globalConfigURL: https://ton.org/global.config.json
    validatorPort: 30001
    liteServerPort: 30003
    validatorConsolePort: 30002
    hostPortsEnabled: true
  keyManagement:
    enabled: false
  env:
  - name: MODE
    value: liteserver
  - name: DUMP
    value: "true"
