replicaCount: 1

image:
  repository: ghcr.io/neodix42/ton-k8s-operator
  tag: 0.1.55
  pullPolicy: IfNotPresent

leaderElection:
  enabled: true

metrics:
  enabled: true

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
