nameOverride: ""
fullnameOverride: ""

namespace:
  create: false

image:
  repository: ghcr.io/neodix42/ton-k8s-operator
  tag: 0.1.49
  pullPolicy: IfNotPresent
  pullSecrets: []

replicaCount: 1

leaderElection:
  enabled: true

metrics:
  enabled: true
  service:
    port: 8443

rbac:
  create: true

serviceAccount:
  create: true
  name: ""

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

podAnnotations: {}
podLabels: {}
nodeSelector: {}
tolerations: []
affinity: {}

extraArgs: []
extraEnv: []

tonNode:
  enabled: false
  name: tonnode
  namespace: ""
  labels: {}
  image: ghcr.io/ton-blockchain/ton-docker-ctrl:v2026.04-amd64
  replicas: 3
  storage:
    tonWorkSize: 400Gi
    myTonCoreSize: 20Gi
    storageClassName: ""
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      cpu: 16000m
      memory: 64Gi
    limits:
      cpu: 128000m
      memory: 256Gi
  nodeSelector: {}
  network:
    globalConfigURL: https://ton.org/global.config.json
    validatorPort: 30001
    quicPort: 31001
    liteServerPort: 30003
    validatorConsolePort: 30002
    hostPortsEnabled: true
    publicIP: ""
  configRefName: ""
  keyManagement:
    enabled: true
    provider: vault
    credentialsSecretRef: ton-vault-creds
    vaultTransitKey: ton-validator
    kmsKeyID: ""
    kmsVendor: aws
    inMemory:
      keysSizeLimit: 128Mi
      walletsSizeLimit: 512Mi
    encryptedBundle:
      pvcSize: 5Gi
      storageClassName: encrypted-sc
      accessModes:
        - ReadWriteOnce
      fileName: keys.bundle.enc
      metaFileName: keys.bundle.meta
    agent:
      image: ghcr.io/ton-blockchain/ton-docker-ctrl:v2026.04-amd64
      resources: {}
  env:
    - name: TON_BRANCH
      value: v2026.04
    - name: ARCHIVE_TTL
      value: "86400"
    - name: STATE_TTL
      value: "86400"
    - name: SYNC_BEFORE
      value: "60"
    - name: VERBOSITY
      value: "1"
    - name: IGNORE_MINIMAL_REQS
      value: "true"
    - name: TELEMETRY
      value: "true"
    - name: MODE
      value: liteserver
    - name: DUMP
      value: "true"
    - name: MYTONCTRL_VERSION
      value: master
    - name: CUSTOM_PARAMETERS
      value: ""
